[tools]
bun = "latest"
dotnet = "latest"
java = "latest"
node = "latest"

[tasks.server-test]
run = "dotnet test -c Release"

[tasks.web-install]
dir = "web"
run = "bun install"

[tasks.web-test]
depends = ["web-install"]
dir = "web"
run = "bun run test"