<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>b841cb76-0f48-444a-ab86-132a7bf866ae</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Google.Cloud.DocumentAI.V1" Version="3.25.0" />
      <PackageReference Include="Google.Cloud.Firestore" Version="4.4.0" />
      <PackageReference Include="Google.Cloud.Storage.V1" Version="4.15.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DocumentProcessingPipeline.Server.Domain\DocumentProcessingPipeline.Server.Domain.csproj" />
    </ItemGroup>

</Project>
