<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>5de90e01-b58c-4571-8dec-fe423eee9494</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\DocumentProcessingPipeline.Server\DocumentProcessingPipeline.Server.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.4.6"/>
    </ItemGroup>
</Project>
