name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: document-pipeline-2026
  REGION: asia-southeast1
  SERVER_SERVICE: backend-dev
  WEB_SERVICE: ${{ secrets.WEB_SERVICE }}
  WORKLOAD_IDENTITY_PROVIDER: projects/338747081006/locations/global/workloadIdentityPools/github/providers/my-repo
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}

jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      SERVER_IMAGE_TAG: ${{ steps.set-tags.outputs.SERVER_IMAGE_TAG }}
      WEB_IMAGE_TAG: ${{ steps.set-tags.outputs.WEB_IMAGE_TAG }}
    steps:
      - id: set-tags
        run: |
          echo "SERVER_IMAGE_TAG=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVER_SERVICE }}:${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "WEB_IMAGE_TAG=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.WEB_SERVICE }}:${{ github.sha }}" >> $GITHUB_OUTPUT

  server-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Mise
        uses: jdx/mise-action@v4

      - name: Run Server Tests
        run: mise run server-test
  
  build-server:
    runs-on: ubuntu-latest
    needs: [ server-tests, initialize ]
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        id: auth
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Login to Google Cloud Artifact Registry
        run: |
          podman login \
          ${{ env.REGION }}-docker.pkg.dev \
          -u oauth2accesstoken \
          -p ${{ steps.auth.outputs.auth_token }}

      - name: Build and push server image
        run: |
          podman build --format docker -t ${{ needs.initialize.outputs.SERVER_IMAGE_TAG }} ./DocumentProcessingPipeline.Server
          podman push ${{ needs.initialize.outputs.SERVER_IMAGE_TAG }}

  build-web:
    runs-on: ubuntu-latest
    needs: [ server-tests, initialize ]
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          token_format: 'access_token'
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Login to Google Cloud Artifact Registry
        run: |
          echo "${{ steps.auth.outputs.access_token }}" | podman login \
          ${{ env.REGION }}-docker.pkg.dev \
          -u oauth2accesstoken \
          --password-stdin

      - name: Build and push web image
        run: |
          podman build --format docker -t ${{ needs.initialize.outputs.WEB_IMAGE_TAG }} ./frontend
          podman push ${{ needs.initialize.outputs.WEB_IMAGE_TAG }}

  deploy-server:
    runs-on: ubuntu-latest
    needs: [ build-server, initialize ]
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        id: auth
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Deploy ${{ env.SERVER_SERVICE }} to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'backend-dev'
          region: ${{ env.REGION }}
          image: ${{ needs.initialize.outputs.SERVER_IMAGE_TAG }}

  deploy-web:
    runs-on: ubuntu-latest
    needs: [ build-web, initialize ]
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          token_format: 'access_token'
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Deploy ${{ env.WEB_SERVICE }} to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.WEB_SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ needs.initialize.outputs.WEB_IMAGE_TAG }}