name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: ${{ secrets.REGION }}
  SERVER_SERVICE: ${{ secrets.SERVER_SERVICE }}
  WEB_SERVICE: ${{ secrets.WEB_SERVICE }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  SERVER_IMAGE_TAG: ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.SERVER_SERVICE }}:${{ github.sha }}
  WEB_IMAGE_TAG: ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.WEB_SERVICE }}:${{ github.sha }}

jobs:
  server-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Mise
        uses: jdx/mise-action@v4

      - name: Run Server Tests
        run: mise run server-test
  
  web-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Mise
        uses: jdx/mise-action@v4

      - name: Run Web Tests
        run: mise run web-test
  
  build-server:
    runs-on: ubuntu-latest
    needs: [ server-tests, web-tests ]
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          token_format: 'access_token'
          service_account: '${{ env.SERVICE_ACCOUNT }}'

      - name: Login to Google Cloud Artifact Registry
        run: |
          echo "${{ steps.auth.outputs.access_token }}" | podman login \
          ${{ env.REGION }}-docker.pkg.dev \
          -u oauth2accesstoken \
          --password-stdin

      - name: Build and push server image
        run: |
          podman build --format docker -t ${{ env.SERVER_IMAGE_TAG }} ./DocumentProcessingPipeline.Server
          podman push ${{ env.SERVER_IMAGE_TAG }}

  build-web:
    runs-on: ubuntu-latest
    needs: [ server-tests, web-tests ]
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          token_format: 'access_token'
          service_account: '${{ env.SERVICE_ACCOUNT }}'

      - name: Login to Google Cloud Artifact Registry
        run: |
          echo "${{ steps.auth.outputs.access_token }}" | podman login \
          ${{ env.REGION }}-docker.pkg.dev \
          -u oauth2accesstoken \
          --password-stdin

      - name: Build and push web image
        run: |
          podman build --format docker -t ${{ env.WEB_IMAGE_TAG }} ./frontend
          podman push ${{ env.WEB_IMAGE_TAG }}

  deploy-server:
    runs-on: ubuntu-latest
    needs: build-server
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          token_format: 'access_token'
          service_account: '${{ env.SERVICE_ACCOUNT }}'

      - name: Deploy ${{ env.SERVER_SERVICE }} to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVER_SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.SERVER_IMAGE_TAG }}

  deploy-web:
    runs-on: ubuntu-latest
    needs: build-web
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          token_format: 'access_token'
          service_account: '${{ env.SERVICE_ACCOUNT }}'

      - name: Deploy ${{ env.WEB_SERVICE }} to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.WEB_SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.WEB_IMAGE_TAG }}